version: '3.8'

services:
  ask_docs_client:
    image: deepak93p/ask-docs-client:latest
    pull_policy: always
    ports:
      - "8502:8502"
    environment:
      - NAME=ask-docs-client
      - ASK_DOCS_SERVER_BASIC_AUTH_USERNAME=username
      - ASK_DOCS_SERVER_BASIC_AUTH_PASSWORD=password
      - ASK_DOCS_SERVER_BASE_URL=http://localhost:8000
    volumes:
      - /tmp/askdocsgpt:/tmp/askdocsgpt