version: '3.8'

services:
  ask_docs_server:
    image: deepak93p/ask-docs-server:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      - NAME=ask-docs-server
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=askdocs
      - MODEL_NAME=gpt-3.5-turbo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s