version: '3.8'

services:
  ask_docs_server:
    image: deepak93p/ask-docs-server:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      - NAME=ask-docs-server
      - BASIC_AUTH_USERNAME=askdocs-user
      - BASIC_AUTH_PASSWORD=askdocs-password
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s