# Copyright (c) 2024 Deepak Pant. All rights reserved.
# This file is part of the AskDocsGPT project.

from pydantic import BaseModel, Field


class PromptInputSchema(BaseModel):
    question: str = Field(..., min_length=3, max_length=4000, description="Input Question for the modal.")


class PromptOutputSchema(BaseModel):
    answer: str = Field(..., description="The answer generated by the model.")
