# Copyright (c) 2024 Deepak Pant. All rights reserved.
# This file is part of the AskDocsGPT project.

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Document(BaseModel):
    page_content: str = Field(..., description="The content of the document.")
    metadata: Optional[dict] = {}  # Add metadata field to the Document model


class QuestionRequest(BaseModel):
    question: str = Field(..., min_length=3, max_length=250, description="Input Question for the modal.")


class AnswerResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the model.")
    source_documents: Optional[List[Document]] = Field(None,
                                                       description="The source documents used to generate the answer.")


class FileType(Enum):
    PDF = "pdf"
